on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      TF_BACKEND_RESOURCE_GROUP_NAME:
        required: true
      TF_BACKEND_STORAGE_ACCOUNT_NAME:  
        required: true

jobs: 
  Login:
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Azure login
      uses: azure/login@v2
      with:
        auth-type: IDENTITY
        client-id:  ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
        subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get Storage Account Key
      id: get-key-st
      run: |
        ACCOUNT_KEY=$(az storage account keys list --resource-group  ${{ secrets.TF_BACKEND_RESOURCE_GROUP_NAME }} --account-name ${{ secrets.TF_BACKEND_STORAGE_ACCOUNT_NAME }}  --query '[0].value' -o tsv)
        echo "ARM_ACCESS_KEY=$ACCOUNT_KEY" >> $GITHUB_ENV