name: Run Azure Login with User-assigned Managed Identity
on: [push]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get Storage Account Key
        id: get-key
        run: |
          ACCOUNT_KEY=$(az storage account keys list --resource-group ${{ secrets.TF_BACKEND_RESOURCE_GROUP_NAME }} --account-name ${{ secrets.TF_BACKEND_STORAGE_ACCOUNT_NAME }}  --query '[0].value' -o tsv)
          echo "ARM_ACCESS_KEY=$ACCOUNT_KEY" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2    

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@enhancement/args
        with:
          tf_actions_subcommand: 'plan'
          args: '-out=plan.tfplan'

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@enhancement/args
        with:
          #tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
          args: 'plan.tfplan'

      # - name: Terraform Apply
      #   if: github.ref != 'refs/heads/main'
      #   run: terraform apply -auto-approve plan=tfplan
